### PR TITLE
Optimize docker images with multi-stage builds.

### PR DESCRIPTION
**Pull request by michaeldimoudis**
Reduces docker images from 1.64Gb to 302Mb (web) and 282Mb (worker).

### CODE REVIEW

**Comment by jimmyp** [comment]
Worth a PR to here too? https://github.com/PageUpPeopleOrg/API-Bootstrap/blob/master/Dockerfile

**Comment by jimmyp** [comment]
@antonfelich @scottabutler this one

**Review by humblelistener — APPROVED** [review]

**Comment by humblelistener** [comment]
close #51 #50

**Comment by humblelistener** [comment]
Thanks @michaeldimoudis

**Pull request merged**
